networks:
  devcontainer:
    internal: false
services:
  devcontainer:
    build:
      context: './'
      dockerfile: './Dockerfile'
      target: 'devcontainer'
    command: 'sleep infinity'
    environment:
      APP_ENV: 'local'
      COMPOSER_CACHE_DIR: '/home/devcontainer/.composer/cache'
      NODE_ENV: 'development'
      NPM_CONFIG_CACHE: '/home/devcontainer/.npm'
    init: true
    networks:
      - 'devcontainer'
    user: 'devcontainer:devcontainer'
    volumes:
      - './:/var/www/html'
      - 'composer-cache:/home/devcontainer/.composer/cache'
      - 'npm-cache:/home/devcontainer/.npm'
volumes:
  composer-cache:
    external: true
    name: 'tomaschochola-composer-cache'
  npm-cache:
    external: true
    name: 'tomaschochola-npm-cache'
